# Exported from Render on 2024-10-10T10:32:11Z
services:
- type: web
  name: Fleets API
  runtime: node
  repo: https://gitlab.com/fleets-team/back-gpe
  plan: starter
  envVars:
  - key: FLEETS_ENV
    sync: false
  - key: DATABASE_URL
    sync: false
  - fromGroup: Base Environment
  region: frankfurt
  buildCommand: pnpm install && pnpm build && pnpm migration:run
  startCommand: pnpm start
  domains:
  - api.fleets-app.fr
  - api.fleets-app.com
  rootDir: backend
version: "1"
