import { FleetsDelaysType } from '@/config/config.type';

const MAX_GATHERING_DELAY = 15;
const MID_GATHERING_DELAY = 10;
const MIN_GATHERING_DELAY = 5;
const MIN_FORMATION_DELAY = 5;
const MIN_DEPARTURE_MINUTES_DELAY = MIN_FORMATION_DELAY + MIN_GATHERING_DELAY;

const MAX_GATHERING_DELAY_SHORT = 5;
const MID_GATHERING_DELAY_SHORT = 3;
const MIN_GATHERING_DELAY_SHORT = 2;
const MIN_FORMATION_DELAY_SHORT = 1;
const MIN_DEPARTURE_MINUTES_DELAY_SHORT =
  MIN_FORMATION_DELAY_SHORT + MIN_GATHERING_DELAY_SHORT;

const FLEETS_DELAYS: FleetsDelaysType = {
  MIN_GATHERING_DELAY,
  MID_GATHERING_DELAY,
  MAX_GATHERING_DELAY,
  MIN_FORMATION_DELAY,
  MIN_DEPARTURE_MINUTES_DELAY,
};

const FLEETS_SHORT_DELAYS: FleetsDelaysType = {
  MIN_GATHERING_DELAY: MIN_GATHERING_DELAY_SHORT,
  MID_GATHERING_DELAY: MID_GATHERING_DELAY_SHORT,
  MAX_GATHERING_DELAY: MAX_GATHERING_DELAY_SHORT,
  MIN_FORMATION_DELAY: MIN_FORMATION_DELAY_SHORT,
  MIN_DEPARTURE_MINUTES_DELAY: MIN_DEPARTURE_MINUTES_DELAY_SHORT,
};

export function getFleetsDelays(useShortDelays: boolean): FleetsDelaysType {
  if (useShortDelays) {
    return FLEETS_SHORT_DELAYS;
  }

  return FLEETS_DELAYS;
}
