const MAX_GATHERING_DELAY = 15;
const MIN_GATHERING_DELAY = 5;
const MIN_FORMATION_DELAY = 5;
const MIN_DEPARTURE_MINUTES_DELAY = MIN_FORMATION_DELAY + MIN_GATHERING_DELAY;

export const FLEETS_DELAYS = {
  MIN_GATHERING_DELAY,
  MAX_GATHERING_DELAY,
  MIN_FORMATION_DELAY,
  MIN_DEPARTURE_MINUTES_DELAY,
};

const MAX_GATHERING_DELAY_SHORT = 5;
const MIN_GATHERING_DELAY_SHORT = 1;
const MIN_FORMATION_DELAY_SHORT = 1;
const MIN_DEPARTURE_MINUTES_DELAY_SHORT =
  MIN_FORMATION_DELAY_SHORT + MIN_GATHERING_DELAY_SHORT;

export const FLEETS_SHORT_DELAYS = {
  MIN_GATHERING_DELAY: MIN_GATHERING_DELAY_SHORT,
  MAX_GATHERING_DELAY: MAX_GATHERING_DELAY_SHORT,
  MIN_FORMATION_DELAY: MIN_FORMATION_DELAY_SHORT,
  MIN_DEPARTURE_MINUTES_DELAY: MIN_DEPARTURE_MINUTES_DELAY_SHORT,
};
